# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53a9a9ba88235142b3636bceb49a64fc1aa6f38ab57aeb06a89721c7246a12f6c4695e4fe796aa5f7a450ac60325a05d142174aa7394c9b55399e122652c7fbd

test:
  secret_key_base: 3a48ef864c017016605d6c92fb41963dd3d396777add6ac9516e0d2b51d9446a76ffda049d33097b7b30ec0d5af740df627c6e48cc037c1db3d33761ec95445e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
